"""anime_table

Revision ID: b35ab3749336
Revises: 
Create Date: 2024-02-28 10:31:44.509887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35ab3749336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Rank', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=250), nullable=True),
    sa.Column('Japanese_name', sa.String(length=250), nullable=True),
    sa.Column('Type', sa.String(length=250), nullable=True),
    sa.Column('Episodes', sa.Float(), nullable=True),
    sa.Column('Studio', sa.String(length=250), nullable=True),
    sa.Column('Release_season', sa.String(length=250), nullable=True),
    sa.Column('Tags', sa.String(length=250), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.Column('Release_year', sa.Float(), nullable=True),
    sa.Column('End_year', sa.Float(), nullable=True),
    sa.Column('Description', sa.String(length=250), nullable=True),
    sa.Column('Content_warning', sa.String(length=250), nullable=True),
    sa.Column('Related_mange', sa.String(length=250), nullable=True),
    sa.Column('Related_anime', sa.String(length=250), nullable=True),
    sa.Column('Voice_actors', sa.String(length=250), nullable=True),
    sa.Column('Staff', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_model')
    # ### end Alembic commands ###
